apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eiwyg
  labels:
    app: eiwyg
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eiwyg
                port:
                  number: 80
